#+TITLE: PyBIND: The Py That BINDs
This directory contains python modules for creating and writing BIND configuration files and zone files.

=dnszone= is not intended or suitable for general manipulation of zones and zone files; use [[http://www.dnspython.org/][dnspython]] for that. Similary, =bindconfig= doesn't read or parse BIND configuration files; try [[https://code.google.com/p/iscpy/][ISCpy]] for that. These were created specifically for /writing/ files rather than parsing or otherwise manipulating them.

Terminology and other reference information have been taken from ZYTRAX, Inc.'s [[http://www.zytrax.com/books/dns][DNS for Rocket Scientists]].

Patches and suggestions are welcome, but I created these of course to address my own needs.

* TODO
  - add ACL support to bindconf
  - move to GitHub
  - register with PyPI
  - add SPF support, other RR types?
  - add DNSSEC support

* Why?
Building zones from scratch with dnspython is tedious and complicated; it wasn't intended for such use. I initially was successful in doing so, but there seemed to be some bugs in writing the zones to files.

* License

Copyright (c) 2012 Brian L. Brush

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
